GardenBuddy/Models/GardenBed.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace GardenBuddy.Models
{
    public class GardenBed
    {
        [Key]
        public int GardenBedId { get; set; }
        [Required]
        public string name { get; set; }

        public ApplicationUser user { get; set; }

        public string userId { get; set; }
        
        public virtual ICollection<PlantGarden> PlantGardens { get; set; }

       


    }
}

GardenBuddy/Models/GardenBedViewModels/AddPlantViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GardenBuddy.Models.GardenBedViewModels
{
    public class AddPlantViewModel
    {
        public virtual ICollection<Plant> Plants { get; set; }

        public Plant Plant { get; set; } 

        public PlantGarden PlantGarden { get; set; }

        public GardenBed GardenBed { get; set; }

        public int GardenBedId { get; set; }

        public int PlantId { get; set; }

        public List<SelectListItem> GardenList { get; set; }


        public List<SelectListItem> PlantList { get; set; }


    
    }
        
}

GardenBuddy/Controllers/GardenBedsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GardenBuddy.Data;
using GardenBuddy.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using GardenBuddy.Models.GardenBedViewModels;
using Microsoft.AspNetCore.Authorization;
using static GardenBuddy.Models.GardenBedViewModels.GardenBedDetailsViewModel;

namespace GardenBuddy.Controllers
{
    public class GardenBedsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public GardenBedsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
            
        }

        // This method will be called every time we need to get the current user
        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: GardenBeds
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var currentUser = await GetCurrentUserAsync();
            var userGarden = _context.GardenBeds.Where(g => currentUser.Id == g.userId);
            return View(await userGarden.ToListAsync());
        }

        // GET: GardenBeds/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gardenBed = await _context.GardenBeds
                .Include(u => u.user)
                .Include(pg => pg.PlantGardens)
                .ThenInclude(p => p.Plant)
                .FirstOrDefaultAsync(m => m.GardenBedId == id);
            if (gardenBed == null)
            {
                return NotFound();
            }

            GardenBedDetailsViewModel viewmodel = new GardenBedDetailsViewModel
            {
                GardenBeds = gardenBed

            };

            viewmodel.totalWidth = gardenBed.PlantGardens
                .GroupBy(rw => rw.Plant)
                .Select(p => new totalRowWidth
                {
                    Plant = p.Key,
                    rowWidth = p.Key.rowWidth * p.Select(l => l.PlantId).Count(),
                }).ToList();



            return View(viewmodel);
        }

        // GET: GardenBeds/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: GardenBeds/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(GardenBed gardenBed)
        {
            ModelState.Remove("User");
            ModelState.Remove("UserId");

            if (ModelState.IsValid)
            {

                var currUser = await GetCurrentUserAsync();
                gardenBed.userId = currUser.Id;
                _context.Add(gardenBed);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(gardenBed);
        }

        // GET: GardenBeds/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gardenBed = await _context.GardenBeds.FindAsync(id);
            if (gardenBed == null)
            {
                return NotFound();
            }
            return View(gardenBed);
        }

        // POST: GardenBeds/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GardenBedId,name")] GardenBed gardenBed)
        {
            if (id != gardenBed.GardenBedId)
            {
                return NotFound();
            }
            ModelState.Remove("User");
            ModelState.Remove("UserId");
            var currUser = await GetCurrentUserAsync();

            if (ModelState.IsValid)


            {
                try
                {
                    gardenBed.userId = currUser.Id;
                    _context.Update(gardenBed);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GardenBedExists(gardenBed.GardenBedId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(gardenBed);
        }

        // GET: GardenBeds/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gardenBed = await _context.GardenBeds
                .FirstOrDefaultAsync(m => m.GardenBedId == id);
            if (gardenBed == null)
            {
                return NotFound();
            }

            return View(gardenBed);
        }

        // POST: GardenBeds/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var gardenBed = await _context.GardenBeds.FindAsync(id);
            _context.GardenBeds.Remove(gardenBed);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> AddPlant()
        {
            var currUser = await GetCurrentUserAsync();


            AddPlantViewModel viewmodel = new AddPlantViewModel
            {
                GardenList = await _context.GardenBeds.Where(u => u.userId == currUser.Id).Select(g => new SelectListItem
                {
                    Text = g.name,
                    Value = g.GardenBedId.ToString()
                }).ToListAsync(),

                PlantList = await _context.Plants.Select(p => new SelectListItem(p.PlantName, p.PlantId.ToString())).ToListAsync()
        };

            return View(viewmodel);
        }

        // POST: GardenBeds/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddPlant(AddPlantViewModel viewmodel)
        {
            viewmodel.PlantGarden = new PlantGarden
            {
                Plant = await _context.Plants.FindAsync(viewmodel.PlantId),
                GardenBed = await _context.GardenBeds.FindAsync(viewmodel.GardenBedId),
                rowNumber = viewmodel.PlantGarden.rowNumber,
                plantCount = viewmodel.PlantGarden.plantCount
                
            };

            if (ModelState.IsValid)
            {

                _context.Add(viewmodel.PlantGarden);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "GardenBeds", new { id = viewmodel.GardenBedId });
            }
            return NotFound();
        }

        // GET: Plants/Details/5
        public async Task<IActionResult> PlantDetail(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plant = await _context.Plants
                .FirstOrDefaultAsync(m => m.PlantId == id);
            if (plant == null)
            {
                return NotFound();
            }

            return View(plant);
        }

        public async Task<IActionResult> EditPlant(int? id)
        {
            var currUser = await GetCurrentUserAsync();


            EditGardenPlantViewModel viewmodel = new EditGardenPlantViewModel
            {
                PlantList = await _context.Plants.Select(p => new SelectListItem(p.PlantName, p.PlantId.ToString())).ToListAsync(),
                PlantGarden = await _context.PlantGardens.FindAsync(id)

            };

            return View(viewmodel);
        }

        // POST: GardenBeds/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPlant(EditGardenPlantViewModel viewmodel)
        {

            var PlantGarden = viewmodel.PlantGarden;
            var GardenBed = await _context.GardenBeds.FindAsync(viewmodel.GardenBedId);
            var Plant = await _context.Plants.FindAsync(viewmodel.PlantGarden.PlantId);
            PlantGarden.GardenBed = GardenBed;
            PlantGarden.Plant = Plant;

            ModelState.Remove("PlantGarden.PlantList");
            ModelState.Remove("PlantGarden.Plants");



            //viewmodel.PlantGarden = new PlantGarden
            //{
            //    Plant = await _context.Plants.FindAsync(viewmodel.PlantId),
            //    rowNumber = viewmodel.PlantGarden.rowNumber,
            //    plantCount = viewmodel.PlantGarden.plantCount,
            //    GardenBedId = viewmodel.GardenBedId,
            //    PlantId = viewmodel.PlantId,
            //    PlantGardenId = viewmodel.PlantGarden.PlantGardenId
            //};

GardenBuddy/Controllers/PlantGardensController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GardenBuddy.Data;
using GardenBuddy.Models;

namespace GardenBuddy.Controllers
{
    public class PlantGardensController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PlantGardensController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: PlantGardens
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.PlantGardens.Include(p => p.GardenBed).Include(p => p.Plant);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: PlantGardens/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plantGarden = await _context.PlantGardens
                .Include(p => p.GardenBed)
                .Include(p => p.Plant)
                .FirstOrDefaultAsync(m => m.PlantGardenId == id);
            if (plantGarden == null)
            {
                return NotFound();
            }

            return View(plantGarden);
        }

        // GET: PlantGardens/Create
        public IActionResult Create()
        {
            ViewData["GardenBedId"] = new SelectList(_context.GardenBeds, "GardenBedId", "name");
            ViewData["PlantId"] = new SelectList(_context.Plants, "PlantId", "Disease");
            return View();
        }

        // POST: PlantGardens/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PlantGardenId,PlantId,GardenBedId,rowNumber,plantCount")] PlantGarden plantGarden)
        {
            if (ModelState.IsValid)
            {
                _context.Add(plantGarden);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GardenBedId"] = new SelectList(_context.GardenBeds, "GardenBedId", "name", plantGarden.GardenBedId);
            ViewData["PlantId"] = new SelectList(_context.Plants, "PlantId", "Disease", plantGarden.PlantId);
            return View(plantGarden);
        }

        // GET: PlantGardens/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plantGarden = await _context.PlantGardens.FindAsync(id);
            if (plantGarden == null)
            {
                return NotFound();
            }
            ViewData["GardenBedId"] = new SelectList(_context.GardenBeds, "GardenBedId", "name", plantGarden.GardenBedId);
            ViewData["PlantId"] = new SelectList(_context.Plants, "PlantId", "Disease", plantGarden.PlantId);
            return View(plantGarden);
        }

        // POST: PlantGardens/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PlantGardenId,PlantId,GardenBedId,rowNumber,plantCount")] PlantGarden plantGarden)
        {
            if (id != plantGarden.PlantGardenId)
            {
                return NotFound();
            }
           
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(plantGarden);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlantGardenExists(plantGarden.PlantGardenId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GardenBedId"] = new SelectList(_context.GardenBeds, "GardenBedId", "name", plantGarden.GardenBedId);
            ViewData["PlantId"] = new SelectList(_context.Plants, "PlantId", "Disease", plantGarden.PlantId);
            return View(plantGarden);
        }

        // GET: PlantGardens/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plantGarden = await _context.PlantGardens
                .Include(p => p.GardenBed)
                .Include(p => p.Plant)
                .FirstOrDefaultAsync(m => m.PlantGardenId == id);
            if (plantGarden == null)
            {
                return NotFound();
            }

            return View(plantGarden);
        }

        // POST: PlantGardens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var plantGarden = await _context.PlantGardens.FindAsync(id);
            _context.PlantGardens.Remove(plantGarden);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "GardenBeds", new { id = plantGarden.GardenBedId });
        }

        private bool PlantGardenExists(int id)
        {
            return _context.PlantGardens.Any(e => e.PlantGardenId == id);
        }
    }
}

GardenBuddy/Views/GardenBeds/AddPlant.cshtml
@model GardenBuddy.Models.GardenBedViewModels.AddPlantViewModel

@{
    ViewData["Title"] = "AddPlant";
}

<h4>Add a plant to your garden</h4>


<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="AddPlant">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div>
                <label class="control-label">Select Garden</label>
                <select asp-for="GardenBedId" class="form-control" asp-items="@Model.GardenList"></select>
            </div>
            <div>
                <label class="control-label">Select Plant</label>
                <select asp-for="PlantId" class="form-control" asp-items="@Model.PlantList"></select>
            </div>
            <div class="form-group">
                <label class="control-label">How Many Plants in this Row?</label>
                <input asp-for="PlantGarden.plantCount" class="form-control" placeholder="How many plants are you planting..."/>
                <span asp-validation-for="PlantGarden.plantCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <p>The same Row Number cannot be used twice</p>
                <label class="control-label">Which Row Number?</label>
                <input asp-for="PlantGarden.rowNumber" class="form-control" placeholder="What row will these plants be in..."/>
                <span asp-validation-for="PlantGarden.rowNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GardenBuddy/Views/GardenBeds/Create.cshtml
@model GardenBuddy.Models.GardenBed

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>GardenBed</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GardenBuddy/Views/GardenBeds/Delete.cshtml
@model GardenBuddy.Models.GardenBed

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GardenBed</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="GardenBedId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GardenBuddy/Views/GardenBeds/Details.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Linq;
@inject SignInManager<ApplicationUser> SignInManager

@model GardenBuddy.Models.GardenBedViewModels.GardenBedDetailsViewModel

@{
    ViewData["Title"] = "Details";
}

<link rel="stylesheet" href="~/css/gardenDetails.css" />

@*<h1>Details</h1>*@
<div>
    <h4>@Html.DisplayFor(model => model.GardenBeds.name)</h4>
    <hr />
    Total Width of Garden: @Html.DisplayFor(model => model.TotalWidth) Inches
    <div class="plantButton">
        <a class="btn btn-primary" asp-action="AddPlant" asp-controller="GardenBeds">Add Plant</a>
    </div>
    <dl class="row">
        @*<dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Plantgarden.)
            </dt>*@
        @*<dd class="col-sm-10">
                @Html.DisplayNameFor(model => model.Plantgarden.rowNumber)
            </dd>*@
    </dl>
</div>
<div>
    <div class="flexcontainer">
    @foreach (var item in Model.GardenBeds.PlantGardens)
    {
        <div class="card" style="width: 18rem">
            @{var photoPath = "~/images/" + (item.Plant.ImagePath ?? "noimage.jpg");
                var currUser = SignInManager.UserManager.GetUserId(User);

            }
            <img class="card-img-top imageThumbnail" src="~/images/@item.Plant.ImagePath"
                 asp-append-version="true" />
            <div class="card-body">
                <h5 class="card-title">
                    <a asp-route-id="@item.PlantId" asp-controller="GardenBeds" asp-action="PlantDetail"> @Html.DisplayFor(modelItem => item.Plant.PlantName)</a>
                </h5>

                <p class="card-text">
                    Row Number: @Html.DisplayFor(modelItem => item.rowNumber)
                </p>
                <p class="card-text">
                    Row Width: @Html.DisplayFor(modelItem => item.Plant.rowWidth) Inches
                </p>
                <p class="card-text">
                    How many plants in Row: @Html.DisplayFor(modelItem => item.plantCount)
                </p>

                <p class="card-text">
                    Space Between @Html.DisplayFor(modelItem => item.Plant.PlantName)s in Row:
                </p>
                <p>
                    @Html.DisplayFor(modelItem => item.Plant.BetweenPlants) Inches
                </p>
              
                    <p>
                      Total Row Length: @(item.plantCount * item.Plant.BetweenPlants) Inches
                  </p>
                <p class="card-text">
                    <a asp-controller="GardenBeds" asp-action="EditPlant" asp-route-id="@item.PlantGardenId">Edit</a>  |   <a asp-controller="PlantGardens" asp-action="Delete" asp-route-id="@item.PlantGardenId">Delete</a>
                </p>
            </div>
            @*<a asp-controller="GardenBeds" asp-action="EditPlant" asp-route-id="@item.PlantGardenId">Edit</a>
            <a asp-controller="PlantGardens" asp-action="Delete" asp-route-id="@item.PlantGardenId">Delete</a>*@
        </div>
    }
    </div>
</div>
<div>
    @*<a asp-action="Edit" asp-route-id="@Model.GardenBeds.GardenBedId">Edit</a> |*@
    <a asp-action="Index">Back to My Gardens</a>
</div>

GardenBuddy/Views/GardenBeds/Edit.cshtml
@model GardenBuddy.Models.GardenBed

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>GardenBed</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="GardenBedId" />
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GardenBuddy/Views/GardenBeds/EditPlant.cshtml
@model GardenBuddy.Models.GardenBedViewModels.EditGardenPlantViewModel
@{
    ViewData["Title"] = "Edit";
}


<h4>Edit Plant in your Garden</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditPlant">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="GardenBedId" value="@Model.PlantGarden.GardenBedId" />
            @*<input type="hidden" asp-for="Pl" value="@Model.PlantGarden.GardenBedId" />*@
            <div class="form-group">
                <label asp-for="PlantGarden.Plant.PlantName" class="control-label"></label>
                <select asp-for="PlantGarden.PlantId" class="form-control" asp-items="@Model.PlantList"></select>
                <span asp-validation-for="PlantGarden.PlantId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlantGarden.rowNumber" class="control-label"></label>
                <input asp-for="PlantGarden.rowNumber" class="form-control" />
                <span asp-validation-for="PlantGarden.rowNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlantGarden.plantCount" class="control-label"></label>
                <input asp-for="PlantGarden.plantCount" class="form-control" />
                <span asp-validation-for="PlantGarden.plantCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="PlantGarden.PlantGardenId" />
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a href='javascript:history.go(-1)'>Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GardenBuddy/Views/GardenBeds/Index.cshtml
@model IEnumerable<GardenBuddy.Models.GardenBed>

@{
    ViewData["Title"] = "Index";
}

@*<h1>My Garden(s)</h1>*@

<p>
    <a asp-action="Create">Create New Garden</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                My Garden(s)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-action="Details" asp-route-id="@item.GardenBedId">@Html.DisplayFor(modelItem => item.name)</a>
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.GardenBedId">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@item.GardenBedId">Delete</a>
                </td>
            </tr>
        }

    </tbody>
</table>

@*<div>
    <a class="btn btn-primary" asp-action="AddPlant" asp-controller="GardenBeds">Add Plant</a>
</div>*@

GardenBuddy/Views/GardenBeds/PlantDetail.cshtml
@model GardenBuddy.Models.Plant

@{
    ViewData["Title"] = "Details";
}


<div>
    <h4>Plant Details</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PlantName):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PlantName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.rowWidth):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.rowWidth)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BetweenPlants):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BetweenPlants)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.groundDepth):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.groundDepth)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Soil):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Soil)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Season):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Season)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Watering):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Watering)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Pruning):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pruning)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Pests):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pests)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Disease):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Disease)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MiscCare):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MiscCare)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Storage):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Storage)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.harvestMethod):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.harvestMethod)
        </dd>
    </dl>
</div>
<div>
    @*<a asp-action="Edit" asp-route-id="@Model.PlantId">Edit</a> |*@
    <a href="javascript:history.go(-1)">Back</a>
</div>